name: Update Mods File

on:
  repository_dispatch:
    types: [update-mods]  # This is the event type that will be triggered from your website

jobs:
  update-mods:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Update mods.txt with the new mod information
      - name: Update mods.txt file
        run: |
          echo "${{ github.event.client_payload.mod_name }} | ${{ github.event.client_payload.mod_link }}" >> mods.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add mods.txt
          git commit -m "Add new mod: ${{ github.event.client_payload.mod_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GIT }}  # Use your custom secret here
