name: Update Mods File

on:
  workflow_dispatch:
    inputs:
      MOD_NAME:
        description: 'Mod Name'
        required: true
      MOD_LINK:
        description: 'GitHub Repo Link'
        required: true

jobs:
  update-mods:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update mods.txt
        run: |
          echo "${{ github.event.inputs.MOD_NAME }} | ${{ github.event.inputs.MOD_LINK }}" >> mods/mods.txt
          git config --global user.name "YourGitHubUsername"
          git config --global user.email "YourEmail@example.com"
          git add mods/mods.txt
          git commit -m "Update mods.txt with new mod: ${{ github.event.inputs.MOD_NAME }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GIT }}
