name: Update Mods

on:
  workflow_dispatch:
    inputs:
      MOD_NAME:
        description: 'Mod Name'
        required: true
      MOD_LINK:
        description: 'Mod GitHub Link'
        required: true

jobs:
  update-mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update mods.txt file
        run: |
          echo "${{ github.event.inputs.MOD_NAME }} | ${{ github.event.inputs.MOD_LINK }}" >> mods.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add mods.txt
          git commit -m "Add new mod: ${{ github.event.inputs.MOD_NAME }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GIT }}
